### ISSUE TITLE
在播放列表只有一首歌曲的情况下,点击上下一首无反应

### ISSUE THREAD

**Issue by JianWenXie** [gao211326/GLMusicBox#6]
在播放列表只有一首歌曲的情况下,点击上下一首无反应
如何让点击上下一首的时候,播放当前歌曲?
此时点击播放也无反应了.
希望作者帮助解决一下，感激!

**Comment by gao211326** [comment]
你好，你现在是要满足什么需求呢？

**Comment by JianWenXie** [comment]
作者大大..
这样,在你的demo里,播放音乐.
退出后台.
会发现控制面板的播放按钮是属于关闭的. 而音乐是正在播放的.
可以解决吗?

**Comment by JianWenXie** [comment]
> 在播放列表只有一首歌曲的情况下,点击上下一首无反应 如何让点击上下一首的时候,播放当前歌曲? 此时点击播放也无反应了. 希望作者帮助解决一下，感激!
